version: '3.3'
services:
  backend:
    restart: always
    build: .
    command: ['bash']
    volumes:
      - .:/var/task
      - ~/.aws/:/root/.aws
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    volumes:
      - dynamo-db:/home/dynamodblocal
    ports:
      - "8000:8000"

volumes:
  dynamo-db:
